<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RootNamespace>Fader.Probe</RootNamespace>
    <AssemblyName>Fader.Probe</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Fader.Core.Audio\Fader.Core.Audio.csproj" />
  </ItemGroup>

</Project>
